#
# This file is a deploys the Logger Daemonset to a Kubernetes cluster.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
  namespace: kube-system
  labels:
    service: logger
spec:
  selector:
    matchLabels:
      service: logger
  template:
    metadata:
      labels:
       service: logger
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      containers:
      - name: logger
        image: omarmciver/lightweight-aks-container-logger:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "5m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        env:
        - name: STORAGE_ACCOUNT_NAME
          value: storageaccountrgmpna925
        - name: STORAGE_ACCOUNT_URL_SUFFIX
          value: blob.core.windows.net
        - name: STORAGE_ACCOUNT_CONTAINER_NAME
          value: akslogger
        - name: BATCH_LOG_UPLOAD_TIME_SECONDS
          value: "60"
        - name: STORE_BY_DATE
          value: 'true'
        - name: WATCH_CONTAINERS
          value: ''
        - name: WATCH_MESSAGE_FILTERS
          value: ''
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azstoragecreds
              key: storagekey
              optional: false
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers